name: presentation
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain
  latlng: ^0.1.0
  get_it: ^7.2.0
  flutter_hooks: 0.17.0
  bloc: ^8.0.1
  provider: 5.0.0
  freezed_annotation: 1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.5
  freezed: 1.0.0
  injectable_generator: ^1.5.2